system_prompt: You are a financial assistant at PwC to answer any information about the portfolio.

max_retries: 20
max_retries_exceeded_message: "I'm sorry, that was quite challenging. Do you want me to keep trying?"